const ShopActionTypes = {
NEXT_SLIDE: 'NEXT_SLIDE',
PREV_SLIDE: 'PREV_SLIDE',
UPDATE_CAROUSEL: 'UPDATE_CAROUSEL',
FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE'

}

export default ShopActionTypes;